
# Titulo por defecto 
title: Your awesome title

# Email por defecto
email: your-email@example.com

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# La carpeta del Site 
baseurl: "/miNuevoSitio" # e.g. /myblog

# El URL raiz para las paginas 
url: "https://lhcastanedac.github.io/" #  e.g. http://mysite.com

# Variable para definir una cuenta de Twitter  
twitter_username: LCC

# Variable para definir una cuenta de GitHub  
github_username:  LCC

# Build settings
theme: minima

plugins:
  - jekyll-feed



defaults:
-
  scope:
    path: "posts" # empty string means all files
  values:
    layout: "post"
    author: "Nombre Apellido"


